services:
  server-tfs:
    build: .
    container_name: "server-tfs"
    depends_on:
      mysql:
        condition: service_healthy
    tty: true
    ports:
      - 4000:4000
    volumes:
      - ./src/:/app/src/
  mysql:
    image: mysql
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
  #   volumes:
  #     - mysql:/var/lib/mysql 
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  client-tfs:
    build: ../2203-wns-etchebest-tfs-front/.
    depends_on:
      - server-tfs
    container_name: "client-tfs"
    ports:
      - 3000:3000
    volumes:
      - ../2203-wns-etchebest-tfs-front/src:/app/src
